### ISSUE TITLE
Installing with setup.py fails on python 3 due to the unicode characters in CONTRIBUTING.rst

### ISSUE THREAD

**Issue by rm-hull** [rm-hull/luma.oled#111]
Reported by @bjerrep

**Comment by thijstriemstra** [comment]
We use rstcheck on the README.rst, maybe it should also run on the other .rst files and hopefully these kind of errors are detected.

**Comment by thijstriemstra** [comment]
@bjerrep any news? have you tried the latest version? Closing ticket, please add some feedback if you want to reopen it.
