### ISSUE TITLE
Badge layout in README.rst

### ISSUE THREAD

**Issue by rm-hull** [rm-hull/luma.oled#117]
@thijstriemstra do you know why the readme badges are not displaying all on one line in github (they used to up until recently):

<img width="257" alt="screen shot 2017-01-13 at 20 27 32" src="https://cloud.githubusercontent.com/assets/1915543/21944592/e4be79d4-d9ce-11e6-947f-bff9b4324cde.png">

The same readme renders properly in PyPi:

<img width="645" alt="screen shot 2017-01-13 at 20 29 52" src="https://cloud.githubusercontent.com/assets/1915543/21944626/1320b346-d9cf-11e6-85d4-99c28f9c3807.png">

This seems to be something specific to reST documents - markdown readme's in other projects dont seem to be affected

**Comment by thijstriemstra** [comment]
Looking at the HTML, it seems that the 'maintained' badge is wrapped in a `p` tag that adds the extra linebreak(s). I'd get rid of the maintained badge or place it as the final badge and accept it will be rendered in it's own `p` tag.

**Comment by rm-hull** [comment]
Its something weird to do with rST space or something
