### ISSUE TITLE
INSTALLATION ERROR DEPENDENCIES NOT MET

### ISSUE THREAD

**Issue by perrycannon** [rm-hull/luma.oled#134]
I received this error
"The following packages have unmet dependencies:
 libsdl1.2-dev : Depends: libdirectfb-dev (>= 0.9.22) but it is not going to be installed
E: Unable to correct problems, you have held broken packages."

after running the apt-get install
"sudo apt-get install python-dev python-pip libfreetype6-dev libjpeg8-dev libsdl1.2-dev"

I added the missing dependency, received a follow on error for unmet dependencies. Each instance I added the unmet dependencies. The install failed.

Thank you
Perry

**Comment by rm-hull** [comment]
Hi Perry, thanks for the bug report - I think that libsdl1.2dev is no longer required (we used to have a dependency on Pygame, but not any more), and Rasbian has moved on. So I updated the docs to reflect that. Let me know if you run into any other issues, but you should just be able to run:

    $ sudo apt-get install python-dev python-pip libfreetype6-dev libjpeg8-dev

**Comment by perrycannon** [comment]
Thank you. I really want to use your library.

Perry

**Comment by thijstriemstra** [comment]
I think we'll eventually run into the same problem with libjpeg8-dev. Wouldn't libjpeg-dev be a safer choice? (and maybe same for libfreetype-dev?)
