### ISSUE TITLE
Approach to using JSON - SH1106 - Google Assistant SDK - AIY

### ISSUE THREAD

**Issue by sheridat** [rm-hull/luma.oled#157]
Type of Raspberry Pi - Pi W and Pi 3

#### Linux Kernel version
Linux ORA 4.9.24-v7+ #993 SMP Wed Apr 26 18:01:23 BST 2017 armv7l GNU/Linux

#### Expected behaviour
> This is a request for some guidance.  I have used your package before to write to a SH1106 that displayed information from MPD ie station name, artist etc and I displayed the information by just simply putting each piece of information on a line.  You helped me get started and it worked perfectly. 

I have a google AIY kit which I am assuming your aware of. It uses the Google Assistant SDK.
The new version of the SDK provides a JSON string object that contains the text of whatever the assistant thinks you said to it. I want to use the SH1106 OLED to display that information

Your software has a lot of different ways to display data and to be honest quite a lot of it is quite difficult to understand 

Could you advise me of which method you would consider to be most appropriate for the display of what should normally be no more than say a dozen words.

Thank You

**Comment by rm-hull** [comment]
have you looked at the documentation: https://luma-oled.readthedocs.io/en/latest/python-usage.html ?

The simplest example is shown there, and there are numerous other [examples](https://github.com/rm-hull/luma.examples) you can try in the companion repo.
