### ISSUE TITLE
module not found

### ISSUE THREAD

**Issue by Pedotech** [rm-hull/luma.oled#171]
#### Type of Raspberry Pi

Raspberry Pi 2B

#### Linux Kernel version

Linux raspberrypi 4.9.41-v7+ #1023 SMP Tue Aug 8 16:00:15 BST 2017 armv7l GNU/Linux

#### Expected behaviour
```
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170124] on linux2
Type "copyright", "credits" or "license()" for more information.
>>> 
============= RESTART: /home/pi/luma.oled/tests/test_ssd1306.py =============

Traceback (most recent call last):
  File "/home/pi/luma.oled/tests/test_ssd1306.py", line 6, in <module>
    from luma.oled.device import ssd1306
ImportError: No module named luma.oled.device
>>> 
```

#### Actual behaviour

luma.oled.device never found

**Comment by thijstriemstra** [comment]
@Pedotech have you followed these instructions? https://luma-oled.readthedocs.io/en/latest/install.html

And what version of Raspbian are you using?

**Comment by Pedotech** [comment]
Thank you so much for all your generous work!
I reinstalled everything on a new sd and it is working fine.
I have an additional oled on SPI. How can I use it? Message is "oled not found at I2C!
Thank you againa

**Comment by rm-hull** [comment]
> I have an additional oled on SPI. How can I use it? Message is "oled not found at I2C!

First, look at the initial example here: https://luma-oled.readthedocs.io/en/latest/python-usage.html. Also, have a read of the [hardware](https://luma-oled.readthedocs.io/en/latest/hardware.html) section.

Try one of the [examples](https://github.com/rm-hull/luma.examples), as follows:

    $ python examples/demo.py --display=ssd1306 --interface=spi

There are a few other config options, but the defaults are sensible and should work out-of-the-box.
