### ISSUE TITLE
Add support for SSD1351 128x128 Color OLED

### ISSUE THREAD

**Issue by rm-hull** [rm-hull/luma.oled#174]
_[this is a placeholder to record progress on implementation of the `ssd1351` device]_

This development was permitted by the kind donation of funds by @svenyonson to purchase https://www.aliexpress.com/item/1-5-inch-Colorful-OLED-Module-SSD1331-128x128-Resolution-for-51-STM32-Arduino/32721463778.html

# Implementation Notes

Code [WIP] on branch: [feature/SSD1351](https://github.com/rm-hull/luma.oled/tree/feature/SSD1351).
Documentation preview: http://luma-oled.readthedocs.io/en/feature-ssd1351/
Datasheet: http://www.hpinfotech.ro/SSD1351.pdf

Item received, close up pics as follows:
![image](https://user-images.githubusercontent.com/1915543/32110043-755bb2ae-bb2e-11e7-89fc-04762fc523da.png)

![image](https://user-images.githubusercontent.com/1915543/32110061-7de278a4-bb2e-11e7-95c4-ac960a431d1d.png)

| OLED Pin | OLED Name | RPi Pin | RPi Function | Remarks |
|----------|----------|---------|----------|-------|
| 1 | GND | P01-20 | GND | Ground |
| 2 | VCC | P01-17 | 3V3 | +3.3V Power |
| 3 | SCL | P01-23 | GPIO 11 (SCLK) | Serial Clock |
| 4 | SDA | P01-19 | GPIO 10 (MOSI) | Serial Data |
| 5 | RES | P01-22 | GPIO 25 | Reset |
| 6 | DC | P01-18 | GPIO 24 | Data/Command |
| 7 | CS | P01-24 | GPIO 8 (CE0) | Chip Select |

**Comment by rm-hull** [comment]
Using @notro's fbtft driver (swapping over RES & DC from prev comment) confirms that the display works OK:

    $ sudo modprobe fbtft_device name=freetronicsoled128
    $ dmesg | grep fbtft_device
    [   63.900658] fbtft_device: module is from the staging directory, the quality is unknown, you have been warned.
    [   63.903323] fbtft_device: GPIOS used by 'freetronicsoled128':
    [   63.903337] fbtft_device: 'reset' = GPIO24
    [   63.903345] fbtft_device: 'dc' = GPIO25
    $ conf2fbmap 1 1

![image](https://user-images.githubusercontent.com/1915543/32136307-5121e130-bc03-11e7-99e8-9f038df78634.png)

**Comment by rm-hull** [comment]
Ok, so we now have a working implementation:

![image](https://user-images.githubusercontent.com/1915543/32136547-5e4d7ece-bc07-11e7-95b6-7112b6efb8f9.png)

![image](https://user-images.githubusercontent.com/1915543/32136550-7d00fc1a-bc07-11e7-9881-01d9eeae417e.png)

Performance on a Raspberry Pi B2:

```
$ python examples/perfloop.py -f conf/ssd1351.conf --framebuffer=full_frame
Testing display rendering performance
Press Ctrl-C to abort test

Display: ssd1351
Interface: spi
Dimensions: 128 x 128
----------------------------------------
#### iter =    651: render time = 60.09 ms, frame rate = 16.61 FPS
```

**Comment by rm-hull** [comment]
Fixed in #177

**Comment by martijnrondeel** [comment]
A few months ago I was searching for a proper library and came across this one but it didn't have support back then. Now it does, thank you so much for supporting SSD1351 👍.

**Comment by nanomesher** [comment]
I have exactly the same display as above

**Tried both connections as below:**

OLED Pin | OLED Name | RPi Pin | RPi Function | Remarks
-- | -- | -- | -- | --
1 | GND | P01-20 | GND | Ground
2 | VCC | P01-17 | 3V3 | +3.3V Power
3 | SCL | P01-23 | GPIO 11 (SCLK) | Serial Clock
4 | SDA | P01-19 | GPIO 10 (MOSI) | Serial Data
5 | RES | P01-22 | GPIO 25 | Reset
6 | DC | P01-18 | GPIO 24 | Data/Command
7 | CS | P01-24 | GPIO 8 (CE0) | Chip Select


OLED Pin | OLED Name | RPi Pin | RPi Function | Remarks
-- | -- | -- | -- | --
1 | GND | P01-20 | GND | Ground
2 | VCC | P01-17 | 3V3 | +3.3V Power
3 | SCL | P01-23 | GPIO 11 (SCLK) | Serial Clock
4 | SDA | P01-19 | GPIO 10 (MOSI) | Serial Data
5 | RES | P01-18 | GPIO 24 | Data/Command
6 | DC | P01-22 | GPIO 25 | Reset
7 | CS | P01-24 | GPIO 8 (CE0) | Chip Select

Checked many times that spi port seems ok

 ls -l /dev/spi*
crw-rw---- 1 root spi 153, 0 Apr 12 15:40 /dev/spidev0.0
crw-rw---- 1 root spi 153, 1 Apr 12 15:40 /dev/spidev0.1

The program runs without error, but I see nothing on the display , any ideas?

:~/luma.examples$ python examples/perfloop.py -f conf/ssd1351.conf --framebuffer=full_frame
Testing display rendering performance
Press Ctrl-C to abort test

Version: luma.oled 2.3.2 (luma.core 1.7.2)
Display: ssd1351
Interface: spi
Dimensions: 128 x 128
------------------------------------------------------------
#### iter =   2945: render time = 43.67 ms, frame rate = 22.87 FPS


Thanks in advance!

**Comment by ayhlai** [comment]
I have exactly the same display as above

**Tried both connections as below:**

OLED Pin | OLED Name | RPi Pin | RPi Function | Remarks
-- | -- | -- | -- | --
1 | GND | P01-20 | GND | Ground
2 | VCC | P01-17 | 3V3 | +3.3V Power
3 | SCL | P01-23 | GPIO 11 (SCLK) | Serial Clock
4 | SDA | P01-19 | GPIO 10 (MOSI) | Serial Data
5 | RES | P01-22 | GPIO 25 | Reset
6 | DC | P01-18 | GPIO 24 | Data/Command
7 | CS | P01-24 | GPIO 8 (CE0) | Chip Select


OLED Pin | OLED Name | RPi Pin | RPi Function | Remarks
-- | -- | -- | -- | --
1 | GND | P01-20 | GND | Ground
2 | VCC | P01-17 | 3V3 | +3.3V Power
3 | SCL | P01-23 | GPIO 11 (SCLK) | Serial Clock
4 | SDA | P01-19 | GPIO 10 (MOSI) | Serial Data
5 | RES | P01-18 | GPIO 24 | Data/Command
6 | DC | P01-22 | GPIO 25 | Reset
7 | CS | P01-24 | GPIO 8 (CE0) | Chip Select

**Checked many times that spi port seems ok**

 ls -l /dev/spi*
crw-rw---- 1 root spi 153, 0 Apr 12 15:40 /dev/spidev0.0
crw-rw---- 1 root spi 153, 1 Apr 12 15:40 /dev/spidev0.1

**The program runs without error, but I see nothing on the display , any ideas?**

:~/luma.examples$ python examples/perfloop.py -f conf/ssd1351.conf --framebuffer=full_frame
Testing display rendering performance
Press Ctrl-C to abort test

Version: luma.oled 2.3.2 (luma.core 1.7.2)
Display: ssd1351
Interface: spi
Dimensions: 128 x 128
------------------------------------------------------------
#### iter =   2945: render time = 43.67 ms, frame rate = 22.87 FPS


Thanks in advance!

**Comment by rm-hull** [comment]
* Double check your wiring
* Paste close-up pics of the front and back of the oled display board as a comment here

**Comment by ayhlai** [comment]
Thanks for your reply.  I have double checked my wiring again and it looks correct.
I have also tried 
- a brand new Raspbian installation
- on both Pi 3 and Pi 3 B+.
- 2 displays I have , both using SSD1351

Wiring

OLED Pin | OLED Name | RPi Pin | RPi Function | Remarks
-- | -- | -- | -- | --
1 | GND | P01-20 | GND | Ground
2 | VCC | P01-17 | 3V3 | +3.3V Power
3 | SCL | P01-23 | GPIO 11 (SCLK) | Serial Clock
4 | SDA | P01-19 | GPIO 10 (MOSI) | Serial Data
5 | RES | P01-18 | GPIO 24 | Reset
6 | DC | P01-22 | GPIO 25 | Data/Command
7 | CS | P01-24 | GPIO 8 (CE0) | Chip Select



All yield same results - no errors, nothing on screen.  It happens on both of my SSD1351.  
Also,  ssd1306 i2c display works without issue.

Here are some photos (both display were tested):

![image](https://user-images.githubusercontent.com/18458970/38769189-5389b4cc-4031-11e8-903f-cd3f08565975.png)

![image](https://user-images.githubusercontent.com/18458970/38769199-6572540a-4031-11e8-8d23-575d0fc78e3b.png)

Any suggestions of how to debug? thanks very much.

**Comment by thijstriemstra** [comment]
@ayhlai can you open a new ticket for this? thanks for the detailed bug reports.

**Comment by rm-hull** [comment]
@thijstriemstra good idea

@ayhlai please create a new issue and we'll try to help you. When you do create it, please also include the command line you used to start the python script and any output it may have shown. If it was one of your own programs, please include that too. Thanks.

**Comment by thijstriemstra** [comment]
> @thijstriemstra good idea

Can you give me these github permissions, seems I'm not able to lock issues right now.

**Comment by rm-hull** [comment]
@thijstriemstra do you know where/what setting I need to change? I can't spot anything obvious.

**Comment by thijstriemstra** [comment]
@rm-hull at the bottom

![screenshot from 2018-04-18 17-46-29](https://user-images.githubusercontent.com/305679/38942962-7a0f7ab2-4330-11e8-9fdb-87d9657a8e05.png)
