### ISSUE TITLE
MPD Info Scrolling

### ISSUE THREAD

**Issue by creisey** [rm-hull/luma.oled#181]
Hi there im on a small webradio project with MPD

im struggeling with getting the "Channels Name" info on the SSD1306  SSD.

i've managed to use the python-mpd2 library to display the currentsong['name'],  

but its not updating somehow. probably the variable is not getting resetted.

do you have any suggestions how i could manage that?

**Comment by thijstriemstra** [comment]
@creisey does it not make more sense to ask the python-mpd2 project for help with this?

**Comment by rm-hull** [comment]
Can you provide a code sample of what you're trying to achieve?
