### ISSUE TITLE
Use OPi.GPIO?

### ISSUE THREAD

**Issue by sgjava** [rm-hull/luma.oled#188]
Is there a way to use OPi.GPIO with the examples?

**Comment by rm-hull** [comment]
You should be able to add `--gpio=OPi.GPIO` to the command-line or a config file and it will use that implementation instead.

**Comment by thijstriemstra** [comment]
If you're using the examples but what about actual code?

**Comment by sgjava** [comment]
@thijstriemstra :
```
from OPi import GPIO
serial = spi(port=1, device=0, gpio=GPIO, gpio_DC=11, gpio_RST=13)
```
@rm-hull that worked!
