### ISSUE TITLE
NEW YEAR 2018

### ISSUE THREAD

**Issue by elpimous** [rm-hull/luma.oled#190]
I wish you all, an happy new year 2018..
See you in next year..
Vincent

**Comment by CRImier** [comment]
I, too, wish you all a happy New Year! I'm thankful for this library because it enables me to do interesting things, and I'm sure that all the ZeroPhone users&developers feel the same when using software powered by `luma.oled` =)

**Comment by rm-hull** [comment]
I didn't know ZeroPhone used luma.oled - awesome !

**Comment by rm-hull** [comment]
And it goes without saying, but huge thanks to everyone involved (especially @thijstriemstra) for making *luma.oled* and all the other sub-projects what they are.

**Comment by thijstriemstra** [comment]
Thanks, you too people!
