### ISSUE TITLE
luma.oled working on TinkerBoard + SSD1306 0.96"

### ISSUE THREAD

**Issue by effebal** [rm-hull/luma.oled#196]
This awesome library works on TinkerBoard and luma.OLED.
This is the configuration:

- TinkerOS 2.04
- ASUS GPIO API for python libraries (includes a full GPIO RPi library)
- i2c SSD 1306 0.96" OLED diplay

Here is a short video showing the oled in action.

https://youtu.be/NiKvo_2GfNw

**Comment by thijstriemstra** [comment]
Thanks for sharing! That 'tinkerboard' looks **a lot** like a Raspberry Pi ;)

**Comment by rm-hull** [comment]
Nice one @effebal !

Was wondering whether we should collate a load of external links showing off what folks have been using the libs for?

**Comment by thijstriemstra** [comment]
The wiki is probably a good place for that?

**Comment by effebal** [comment]
If I could express my humble opinion, the issue reporting on github is not so good for this kind of news; anyway at the moment it is a good place where sharing.
@thijstriemstra: a dedicated section in the wiki could be the best solution.

**Comment by thijstriemstra** [comment]
@effebal can add a link/section to the documentation to points to a wiki page (that we'll create then)?
