### ISSUE TITLE
Missing installation instruction?

### ISSUE THREAD

**Issue by philpugh51** [rm-hull/luma.oled#204]
New installation on Raspberry Pi Zero, Debian Stretch and Python3 (3.5)
All went well until attempts to run example programs.

I am using an sh1106 OLED display on I2C interface.

On running any example got the error:-
```
 $ python3 examples/demo.py -d SH1106
Traceback (most recent call last):
  File "examples/demo.py", line 17, in <module>$ sudo apt-get install libopenjp2-7-dev
    from luma.core.render import canvas
  File "/usr/local/lib/python3.5/dist-packages/luma/core/render.py", line 5, in <module>
    from PIL import Image, ImageDraw
  File "/usr/local/lib/python3.5/dist-packages/PIL/Image.py", line 58, in <module>
    from . import _imaging as core
ImportError: libopenjp2.so.7: cannot open shared object file: No such file or directory
```
**Solved the issue** by installing the missing library thus:

$ sudo apt-get install libopenjp2-7-dev

Everything OK after this - didn't spot this step in the instructions.

#### Type of Raspberry Pi

Pi Zero V1.3 (non-wifi)

#### Linux Kernel version
Linux  4.14.30+ #1102 Mon Mar 26 16:20:05 BST 2018 armv6l GNU/Linux
.

**Comment by rm-hull** [comment]
Ok thanks, will add a note to the install instructions

:+1:
