### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by sgsungeng** [rm-hull/luma.oled#220]
I clone the `luma.oled` to raspberry pi. And use 'python setup install' to install.
But meet this error:
`error in luma.oled setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.`
what should I do?

**Comment by thijstriemstra** [comment]
@Gadgetoid is right, it's likely a setuptools issue. Did you fix it @sgsungeng?
