### ISSUE TITLE
Support for SSD1309

### ISSUE THREAD

**Issue by nvl1109** [rm-hull/luma.oled#222]
Hi,
I just wonder if any plan to support SSD1309 LCD? Thank you.

**Comment by rm-hull** [comment]
If we can get hold of a device, and the datasheet is readily available, then it should be pretty straightforward to add support for SSD1309

**Comment by jonnedeprez** [comment]
I would also be interested. Maybe [this documentation](http://www.hpinfotech.ro/SSD1309.pdf) can help?

**Comment by thijstriemstra** [comment]
@jonnedeprez having an actual device is also needed to verify. If you or anyone can send one to @rm-hull I'm sure he wants to take a look at it.

**Comment by rm-hull** [comment]
I've just ordered one from AliExpress ...

**Comment by thijstriemstra** [comment]
@rm-hull can you also add a conf file for ssd1309 in the examples?
