### ISSUE TITLE
The screen will stop refreshing on RaspberryPi after a moment.

### ISSUE THREAD

**Issue by aisakong** [rm-hull/luma.oled#226]
The screen will stop refreshing on RaspberryPi after a moment.

**Comment by rm-hull** [comment]
Going to need a bit more information before we can help...

**Comment by aisakong** [comment]
[WeChatSight119.mp4.zip](https://github.com/rm-hull/luma.oled/files/2597923/WeChatSight119.mp4.zip)

I am very sorry to reply to you now. The attachment is the case of running the example. If you need any information, please reply me, thank you.

**Comment by rm-hull** [comment]
Hi @aisakong, I watched the video but couldn't determine what the problem was from the clip you recorded. Can you explain what the issue is in relation to the video?

**Comment by thijstriemstra** [comment]
No feedback, closing.
