### ISSUE TITLE
sh1106 on Cubieboard?

### ISSUE THREAD

**Issue by PrestonL** [rm-hull/luma.oled#236]
Trying to run the example with the Cubieboard 2 on an spi interface for an SH1106, but program outputs "GPIO access not available".  Adding "--gpio RPi.GPIO" returns "RuntimeError: This module can only be run on a Raspberry Pi!".

#### Type of Raspberry Pi
Cubieboard 2

#### Linux Kernel version

Linux mylittletoy 3.4.79-sun7i #19 SMP PREEMPT Fri Oct 10 03:20:03 CST 2014 armv7l GNU/Linux

#### Expected behaviour

Example should play

#### Actual behaviour

```
# python ./examples/terminal.py -d sh1106 -i spi
Version: luma.oled 3.1.0 (luma.core 1.8.2)
Display: sh1106
Interface: spi
Dimensions: 128 x 64
------------------------------------------------------------
usage: terminal.py [-h] [--config CONFIG] [--display] [--width WIDTH]
                   [--height HEIGHT] [--rotate] [--interface]
                   [--i2c-port I2C_PORT] [--i2c-address I2C_ADDRESS]
                   [--spi-port SPI_PORT] [--spi-device SPI_DEVICE]
                   [--spi-bus-speed SPI_BUS_SPEED] [--spi-cs-high SPI_CS_HIGH]
                   [--spi-transfer-size SPI_TRANSFER_SIZE] [--gpio GPIO]
                   [--gpio-mode GPIO_MODE]
                   [--gpio-data-command GPIO_DATA_COMMAND]
                   [--gpio-reset GPIO_RESET] [--gpio-backlight GPIO_BACKLIGHT]
                   [--block-orientation] [--mode] [--framebuffer] [--bgr]
                   [--h-offset H_OFFSET] [--v-offset V_OFFSET]
                   [--backlight-active] [--transform] [--scale SCALE]
                   [--duration DURATION] [--loop LOOP]
                   [--max-frames MAX_FRAMES]
terminal.py: error: GPIO access not available
```

Display does nothing

**Comment by rm-hull** [comment]
So as you have probably gathered, we need a GPIO library which is compatible with RPi.GPIO to make this work on your cubieboard.

There is another library called OPi.GPIO which was originally written for OrangePi boards which bridged this gap for that device, and it has been successfully extended by other folks to cater for other SBCs. It may be possible to extend it again for your use case, depending on how the cubieboard maps it's GPIO pins.

**Comment by PrestonL** [comment]
It looks like this model works just fine with i2c, my device and one I saw on the web had the VCC/GND reversed, even though they looked identical (I have my OLED mounted in an enclosure and I could only see the pins from the back).  It does look like GPIO on Cubieboard may be problematic, but i2c on Cubieboard runs just fine (just make sure it's wired in right!).
