### ISSUE TITLE
Displaying images in canvas

### ISSUE THREAD

**Issue by iv-med** [rm-hull/luma.oled#237]
From the examples I have seen and tried , so display a picture such as png, I need to use the device.display method. Is it possible to display an image within a canvas.

What I would like to do is to display an image inside
with canvas(device, dither=True) as draw:
so that I can have a mixture of text and png in one screen, similar to colors.py example but displaying the canvas and image at the same time.

Is it possible?

Thanks for this great library.

**Comment by rm-hull** [comment]
@iv-med - see response here: https://github.com/rm-hull/luma.examples/issues/87#issuecomment-451690303
