### ISSUE TITLE
Content in portrait mode in RPi oversized & stretched

### ISSUE THREAD

**Issue by jerzyks** [rm-hull/luma.oled#241]
Hello, the display is not able to work properly in portrait mode and the content becomes stretched and oversized. Is there any solution for this problem?

Equipment - Raspberry Pi zero
Interface - SPI
Driver - SH1106
Font - default

Basic script:
```
# Configure the serial port
serial = spi (device = 0, port = 0)
device = sh1106 (serial, rotate = 3)
```

Best regards Jerzy

![2](https://user-images.githubusercontent.com/18427637/51215025-e816ce00-191f-11e9-960d-f7d681e02b03.jpeg)
![1](https://user-images.githubusercontent.com/18427637/51215026-e816ce00-191f-11e9-86c2-a12bf5bb08b7.jpeg)

**Comment by JackJagt** [comment]
I noticed the same problem on Raspberry py 3
![Eye-Portrait](https://user-images.githubusercontent.com/36696633/54315740-4dfd9a00-45df-11e9-9e0e-547ebf509b0d.gif)
![Eye-landscape](https://user-images.githubusercontent.com/36696633/54315744-4fc75d80-45df-11e9-95e1-a332393a031a.gif)
Both are stretched

**Comment by rm-hull** [comment]
@JackJagt can you post the python program you are using to do the animation please?

**Comment by thijstriemstra** [comment]
ping @JackJagt

**Comment by JackJagt** [comment]
Hello thijs
I succeeded to solve the problem bij changing  the origen coordidates 

> ping @JackJagt
