### ISSUE TITLE
brightness control how to

### ISSUE THREAD

**Issue by riker65** [rm-hull/luma.oled#246]
Hi
in the docu I could not find the way how to control brightness.
do you have an example?
or the link?

Thanks

**Comment by riker65** [comment]
Hi
in the docu I could not find the way how to control brightness.
do you have an example?
 or the link?

Thanks

**Comment by rm-hull** [comment]
https://luma-oled.readthedocs.io/en/latest/api-documentation.html#luma.oled.device.ssd1306.contrast

**Comment by riker65** [comment]
ok thanks will check that.
