### ISSUE TITLE
font size how to

### ISSUE THREAD

**Issue by riker65** [rm-hull/luma.oled#247]
Hi
wondering how to change font size here?
Thanks for hints
T

**Comment by riker65** [comment]
Hi
wondering how to change font size here?
Thanks for hints
T

**Comment by rm-hull** [comment]
what have you tried so far?

**Comment by riker65** [comment]
actually how to add new fonts to your libraries?

sorry , I am a beginner.

Thanks

**Comment by RBYoureLate** [comment]
```
FontTemp = ImageFont.truetype("./TestFont.otf",16)
draw.text((0, 0), "Example Text", font=FontTemp)
```
You can try something similar to this, you will obviously need to change the font to a file you have on your system and place this into the appropriate canvas drawing.

**Comment by riker65** [comment]
thanks 
works solved
