### ISSUE TITLE
Dependency to luma.core breaks python 2.7 support

### ISSUE THREAD

**Issue by dhrone** [rm-hull/luma.oled#285]
With the release of luma.core 1.14.0 which does not support python 2.7, there is a dependency break when attempting to install luma.oled using python 2.7 as the install_requires dependency within setup.py:68 specifies luma.core>=1.12.0. As 1.14.0 is the current version that is what gets pulled in breaking the build.  Adding luma.core 1.13.0 in requirements.txt before luma.oled does resolve the break.

**Comment by rm-hull** [comment]
Sorry, all the luma packages will not support py2.7 soon.
