### ISSUE TITLE
Python Usage example: parallel not in luma.core.interface.serial

### ISSUE THREAD

**Issue by z-arnott** [rm-hull/luma.oled#301]
Hi, 
I did the [Python Usage]( https://luma-oled.readthedocs.io/en/latest/python-usage.html) example from the documentation with the SSD1306.
![image](https://user-images.githubusercontent.com/50159450/94853197-045ee500-03f9-11eb-8f79-ec124ac9958b.png)

#### Type of Raspberry Pi
>Raspberry Pi 4B

#### Linux Kernel version
>Linux raspberrypi 5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l GNU/Linux

#### Issue
> I wasn't able to import parallel from from luma.core.interface.serial. I didn't see it in the file anywhere when I checked
```
from luma.core.interface.serial import i2c, spi, parallel, pcf8574
```

#### Fix
>I was able to fix this issue by changing to:
```
from luma.core.interface.serial import i2c, spi, pcf8574
import luma.core.interface.parallel as parallel
```

**Comment by thijstriemstra** [comment]
good catch!
