### ISSUE TITLE
Add documentation about last luma.oled that supports Python 2.7

### ISSUE THREAD

**Issue by thijstriemstra** [rm-hull/luma.oled#317]
Upgrade section in readme for example.

**Comment by thijstriemstra** [comment]
It'll probably pull in latest luma.core though..

**Comment by rm-hull** [comment]
i guess if anyone is determined to use py2.7 then they would have to pin luma.core to the last supported version too

**Comment by thijstriemstra** [comment]
Opened https://github.com/rm-hull/luma.core/issues/220 for that.
