### ISSUE TITLE
Micropython support (RPi Pico)

### ISSUE THREAD

**Issue by Superkris83** [rm-hull/luma.oled#326]
This looks like a nice and complete library. Thank you for creating it!

I'm however not that much interested in using it for a "regular" RPi's. I would be great if there could be a port to MicroPhyton. I found a older post from 18, but maybe MicroPhyton has matured enough by now and the Pi Pico is a very nice platform.

Currently the Pi Pico is lacking decent oled libraries. The libraries that are out there are a bit basic, and dont support that many displays. For example the SSD1233 that i like to use.

Would a port be possible?

**Comment by thijstriemstra** [comment]
Marking as a duplicate of #216
