### ISSUE TITLE
Support ILI9488 3.5" (320x480) displays

### ISSUE THREAD

**Issue by TCB13** [rm-hull/luma.oled#332]
Hello,

Are there any plans to support for 3.5" (320x480) displays with the ILI9488 chip? Or anyone already did it?

Examples of devices: 
- http://www.lcdwiki.com/3.5inch_SPI_Module_ILI9488_SKU:MSP3520
- https://pt.aliexpress.com/item/32985467436.html?algo_exp_id=d2a973dd-545d-4a92-8b61-e427dcc58f4c-1&pdp_ext_f=%7B%22sku_id%22%3A%2266802769934%22%7D

Thank you.

**Comment by TCB13** [comment]
Is there any restriction on the display technology from a technical standpoint? Will that impact decision to include or not to include it?

Thank you.

**Comment by thijstriemstra** [comment]
I think it belongs in the luma.lcd project.

**Comment by TCB13** [comment]
Oh I'm sorry, I was aware that such project existed. Thank you. :)
