### ISSUE TITLE
SSD1351 128x128 Color Issue

### ISSUE THREAD

**Issue by yuniq-neko** [rm-hull/luma.oled#340]
#### Type of Raspberry Pi
Raspberry Pi 4B (4GB)

#### Linux Kernel version
Linux RPi-Dash-Cluster 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux

#### Expected behaviour
RGB = RGB

#### Actual behaviour
RGB ≠ RGB

Red and Blue seem to have swapped, resulting in the palette becoming "BGR".

**Comment by yuniq-neko** [comment]
Photo: ![SwappedRedAndBlue](https://user-images.githubusercontent.com/14962951/163776331-e0370998-3a00-44e1-b430-f02b0a756a28.jpg)

**Comment by rm-hull** [comment]
If you look here (https://luma-oled.readthedocs.io/en/latest/api-documentation.html#luma.oled.device.ssd1351) at the API docs, there is a `bgr=` flag you can set to true. This should resolve the issue.

**Comment by yuniq-neko** [comment]
Apologies on the delay on responding to this, adding --bgr does indeed fix the issue. :)
