### ISSUE TITLE
   from oled.device import ssd1306, sh1106 ModuleNotFoundError: No module named 'oled'

### ISSUE THREAD

**Issue by StefCoders** [rm-hull/luma.oled#380]
#### Type of Raspberry Pi

 RPi 4 2gb

#### Linux Kernel version

Linux piaware 5.15.76-v7l+ #1597 SMP Fri Nov 4 12:14:58 GMT 2022 armv7l GNU/Linux

#### Expected behaviour

To just run.

#### Actual behaviour
```python
   from oled.device import ssd1306, sh1106 
ModuleNotFoundError: No module named 'oled'
```

**Comment by thijstriemstra** [comment]
try: from luma.oled.device import ssd1306, sh1106

**Comment by StefCoders** [comment]
Worked but.. Traceback (most recent call last):
  File "/home/pi/adsb.py", line 38, in <module>
    from luma.oled.device import ssd1306, sh1106
  File "/home/pi/.local/lib/python3.9/site-packages/luma/oled/device/__init__.py", line 38, in <module>
    from luma.core.device import device, parallel_device
  File "/home/pi/.local/lib/python3.9/site-packages/luma/core/device.py", line 9, in <module>
    from PIL import Image
  File "/home/pi/.local/lib/python3.9/site-packages/PIL/Image.py", line 82, in <module>
    from . import _imaging as core
ImportError: libopenjp2.so.7: cannot open shared object file: No such file or directory

**Comment by StefCoders** [comment]
The python code is https://github.com/jprochazka/adsb-receiver/blob/master/build/display/current_total-aircraft_with-positions.py

**Comment by StefCoders** [comment]
Traceback (most recent call last):
  File "/home/pi/adsb.py", line 39, in <module>
    from oled.render import canvas
ModuleNotFoundError: No module named 'oled'

**Comment by thijstriemstra** [comment]
you need to install the Pillow system dependencies, try: sudo apt-get install python3-pillow

**Comment by thijstriemstra** [comment]
did you manage to resolve it @StefCoders?

**Comment by StefCoders** [comment]
Yep.
